version: 1.0.{build}
os: Visual Studio 2015
configuration:
- Release
- Debug
build:
  project: C:\projects\amd-codexl-analyzer\CodeXL\AllProjectsBuild\CodeXLAnalyzerStandAlone.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: 'CodeXL\AllProjectsBuild\..\Output\$(configuration)\bin\*.exe'
